### ISSUE TITLE
Produccion

### ISSUE THREAD

**Issue by argueta15** [AngelMunoz/sails-nuxt#1]
Hola amigo, me encanto tu framework has hecho un excelente trabajo. Tengo un problema para hacer el deploy a producción. ¿Como se hace?. he intentando con yarn run prod, sails lift --prod,  yarn run start y no mas no puedo.

**Comment by AngelMunoz** [comment]
Hola, hmm sinceramente no lo he comprobado, pero basandome en este package.json https://github.com/nuxt-community/express-template/blob/master/template/package.json#L9
casi estoy seguro que primero tienes que hacer un `nuxt build` y de ahi hacer tu `node app.js --production` o `sails lift --prod`, en una oportunidad que tenga lo reviso

**Comment by argueta15** [comment]
va yo también ando checando como se puede hacer. Muchas gracias.

**Comment by AngelMunoz** [comment]
hice unos cambios, puedes probar la ultima version y correr `npm start`? deberia de funcionar sin problemas

**Comment by argueta15** [comment]
Excelente amigo, funciona todo bien, yo había puesto: 
`"scripts": {
    "start": "NODE_ENV=production node app.js",
    "test": "npm run lint && npm run custom-tests && echo 'Done.'",
    "lint": "node ./node_modules/eslint/bin/eslint . --max-warnings=0 && echo '✔  Your code looks good.'",
    "custom-tests": "echo \"(No other custom tests yet.)\" && echo",
    "debug": "node debug app.js",
    "dev": "node app.js --development",
    "prod": "nuxt build &&  node app.js --production"
  },`

**Comment by argueta15** [comment]
Tengo algunos ejemplos, si quieres te los paso para que los revises y si quieres me pones como contribuidor y te puedo ayudar a tener actualizado y hacer ejemplos que tu me digas.

**Comment by AngelMunoz** [comment]
perfecto, sobre los demas ejemplos, si quieres puedes subirlos a tu propio repositorio y te ayudo con esos, no hay problema
