### ISSUE TITLE
Users don't seem to be saved

### ISSUE THREAD

**Issue by cirosantilli** [AngelMunoz/sails-nuxt#3]
At 37da5ce0aa5727b04af85c924686a2bdba5216c3 then http://localhost:1337/users SAVE USER does not seem to have any effect on the website, nor does it show under .tmp.

Would be cool to at least save the users and list them.

Shame, Sails should have this kind of setup as a default.

Would also be cool to ensure that all content pages are at least reachable JS disabled for SEO which is one big motivation for SSR, currently left navbar does not show without js, and chat messages don't show without JS.

All best.

**Comment by AngelMunoz** [comment]
>At [37da5ce](https://github.com/AngelMunoz/sails-nuxt/commit/37da5ce0aa5727b04af85c924686a2bdba5216c3) then http://localhost:1337/users SAVE USER does not seem to have any effect on the website, nor does it show under .tmp

I did a couple of updates few weeks ago perhaps something broke there I did test on my machine before pushing though not sure what's going on there.

Crud operations are out of the scope of this _boilerplate_ it was just a cool thing I tried to share.
That being said though is very trivial to just plug the database adapter + the connection settings.

>Would also be cool to ensure that all content pages are at least reachable JS disabled for SEO which is one big motivation for SSR, currently left navbar does not show without js, and chat messages don't show without JS.

Contributions are always welcome!

**Comment by AngelMunoz** [comment]
I just gave this template an update and fixed some issues on the save/update user
if there are any more concerns please open a new issue
